version: '3.1'
services:
  app:
    container_name: customer-service
    image: customer-service
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s 
    ports:
      - "5432:5432"   
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customerdb
      - POSTGRES_HOST_AUTH_METHOD=trust